import type { NextPage } from "next"
import Head from "next/head"
import { useEffect, useState } from "react"
import { useUnmountAsync } from "src/hooks"
import { services } from "src/services"
import { getRandomIntByRange } from "src/utils"
import styles from "../styles/Home.module.css"
import { Box, Spinner } from "@chakra-ui/react"
import { Image } from "@chakra-ui/react"
import { Character } from "src/models"

const Home: NextPage = () => {
  const { callAsync, loading } = useUnmountAsync()
  const [character, setCharacter] = useState<Character>()

  useEffect(() => {
    const initialCall = async () => {
      const randomCharacterId = getRandomIntByRange(0, 288)
      const response = await callAsync({
        asyncFn: () => services.character.getOne(randomCharacterId)
      })
      setCharacter(response)
    }
    initialCall()
  }, [callAsync])

  return (
    <div className={styles.container}>
      <Head>
        <title>Rick And Morty Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        backgroundImage={`url("/assets/images/bg.png")`}
        minHeight="100vh"
        backgroundRepeat="no-repeat"
        backgroundSize="cover"
        backgroundPosition="center"
        display="flex"
        flexDir="column"
        alignItems="center"
      >
        <Image
          src="/assets/images/logo.png"
          alt={character?.name}
          width="500px"
        />
        <Box display="flex" flexDir="column" marginTop="10rem">
          {loading ? (
            <Spinner color="white" />
          ) : (
            <Image
              src={character?.image}
              alt={character?.name}
              height="300"
              objectFit="contain"
            />
          )}
        </Box>
      </Box>
    </div>
  )
}

export default Home
