export * from "./character/aggregates/characterGender.model"
export * from "./character/aggregates/characterLocation.model"
export * from "./character/aggregates/characterStatus.model"
export * from "./character/character.model"
export * from "./location/location.model"
export * from "./triviaOptions/triviaOption.model"
